name: GoldDigger
main: com.wasteofplastic.golddigger.GoldDigger
version: {$version}
description: Turns stone into gold ingots!
author: tastybento
commands:
    digdig:
        description: Makes stone to dig

